baseURL = "https://gabsoamn.github.io/"
languageCode = "fr-ca"
defaultContentLanguage = "fr"
author = "Gabriela Mendonca"
title = "Gabriela's Blog"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

publishdir = "../docs"

[params]
    homepage = false
    avatar = "/images/self.jpg"
    subtitle = "Plein d'imagination et de rêves!"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    url = "https://github.com/gabisoamn"